version: "3.8"
services:
  frontend:
    container_name: frontend
    image: wallcalendar:dev
    build:
      context: ./ #if your Dockerfile is not at the same level change the path here (./frontend)
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:Z
      - /app/node_modules:Z
      - /app/.next:Z
    ports:
      - 3000:3000
      - 9230:9230
      - 9229:9229
